EFCoreRepositoryPatternDemo/Controllers/ExperiencePortalController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using ExperiencePostCoreWebApp.Models;
using System.IO;

namespace ExperiencePostCoreWebApp.Controllers
{
    public class ExperiencePortalController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ExperiencePortalController(IEmployeeRepository employeeRepository, IWebHostEnvironment hostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _hostEnvironment = hostEnvironment;

        }
        // GET: EmployeesPortalController
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Employee employee)
        {
            Employee emp = _employeeRepository.GetEmployee(employee);
            if (emp != null)
            {
                HttpContext.Session.SetInt32("EmployeeID", emp.EmpID);
                return RedirectToAction("Details");
            }
            else
            {
                ViewData["Status"] = "Invalid user id or password";
                return View();
            }


        }
        // GET: EmployeesPortalController/Details/5
        public ActionResult Details()
        {
            if (HttpContext.Session.GetInt32("EmployeeID")!=null)
            {
                int id = Convert.ToInt32(HttpContext.Session.GetInt32("EmployeeID"));
                Employee employee = _employeeRepository.GetEmployeeByID(id);
                ViewBag.EmpID = employee.EmpID;

                ViewBag.FirstName = employee.FirstName;
                ViewBag.LastName = employee.LastName;
                ViewBag.CellNumber = employee.CellNumber;
                ViewBag.Email = employee.Email;
                ViewBag.ProfilePicture = employee.ProfilePicture;


                IEnumerable<Skill> skills = _employeeRepository.GetAllSkill(employee.EmpID);
                ViewBag.TotalYearsOfExp = skills.Sum(s => s.ExperienceInYears);
                return View(skills);
            }
            else
            {
                return RedirectToAction(nameof(Index));

            }
        }

        // GET: EmployeesPortalController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeesPortalController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind("EmpID,FirstName,LastName,Password,CellNumber,Email")] Employee Employee)
        {
            if (ModelState.IsValid)
            {
                _employeeRepository.Add(Employee);

                return RedirectToAction(nameof(Index));
            }
            return View(Employee);


        }

        [HttpGet]
        public ActionResult CreateSkill()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSkill(Skill skill)
        {
            if (ModelState.IsValid)
            {
                int id = Convert.ToInt32(HttpContext.Session.GetInt32("EmployeeID"));
                skill.EmpID = id;
                _employeeRepository.AddSkill(skill);

                return RedirectToAction(nameof(Details));
            }
            return View(skill);
        }
        // GET: EmployeesPortalController/Edit/5
        public ActionResult Edit(int id)
        {
            Employee employee = _employeeRepository.GetEmployeeByID(id);

            return View(employee);
        }

        // POST: EmployeesPortalController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Employee employee)
        {
            try
            {
                //Edit profile
                    // Delete Existing Image from Upload folder
                    //delete images from wwwroot/Upload folder
                string imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Upload", employee.ProfilePicture);
                if (System.IO.File.Exists(imagePath) && employee.ProfilePicture!= "NoImage.png")
                {
                    System.IO.File.Delete(imagePath);
                }
                // Assign updated image in database
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(employee.ImageFile.FileName);
                string extension = Path.GetExtension(employee.ImageFile.FileName);
                employee.ProfilePicture = fileName = fileName + DateTime.Now.ToString("yyyymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Upload/", fileName);

                using (FileStream fileStream = new FileStream(path, FileMode.Create))
                {
                  await  employee.ImageFile.CopyToAsync(fileStream);
                }


                // Update record



                _employeeRepository.Update(employee);

                return RedirectToAction(nameof(Details));
            }
            catch
            {
                return View();
            }
        }

       
        [HttpGet]
        // GET: EmployeesPortalController/Delete/5
        public ActionResult Delete(int id)
        {
            Skill skill = _employeeRepository.GetSkill(id);
            return View(skill);
        }

        // POST: EmployeesPortalController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Skill skill)
        {
            try
            {
                _employeeRepository.DeleteSkill(skill.SkillId);
                return RedirectToAction(nameof(Details));
            }
            catch
            {
                return View();
            }
        }

       
        [HttpGet]
        public ActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction(nameof(Index));

        }


    }
}

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/Create.cshtml
@model ExperiencePostCoreWebApp.Models.Employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_BeforeLayout.cshtml";
}

<h1>REGIRTER YOURSELF</h1>

<h4>Experience Post Portal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellNumber" class="control-label"></label>
                <input asp-for="CellNumber" class="form-control" />
                <span asp-validation-for="CellNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Login</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/CreateSkill.cshtml
@model ExperiencePostCoreWebApp.Models.Skill

@{
    ViewData["Title"] = "CreateSkill";
    Layout = "~/Views/Shared/_AfterLayout.cshtml";
}

<h1>CreateSkill</h1>

<h4>Skill</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSkill">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                    <label asp-for="SkillId" class="control-label"></label>
                    <input asp-for="SkillId" class="form-control" />
                    <span asp-validation-for="SkillId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EmpID" class="control-label"></label>
                    <input asp-for="EmpID" class="form-control" />
                    <span asp-validation-for="EmpID" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="SkillName" class="control-label"></label>
                <input asp-for="SkillName" class="form-control" />
                <span asp-validation-for="SkillName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceInYears" class="control-label"></label>
                <input asp-for="ExperienceInYears" class="form-control" />
                <span asp-validation-for="ExperienceInYears" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Skill" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details">Back to Dashboard</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/Delete.cshtml
@model ExperiencePostCoreWebApp.Models.Skill

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AfterLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Skill</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SkillId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SkillId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmpID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmpID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SkillName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SkillName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ExperienceInYears)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExperienceInYears)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="SkillId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details">Back to Dashboard</a>
    </form>
</div>

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/Details.cshtml
@model IEnumerable<ExperiencePostCoreWebApp.Models.Skill>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AfterLayout.cshtml";
}

<h1 class="display-2 text-info">Dashboard</h1>

<p>

</p>
<div>
    <div class="card">
        @*src="@("~/Upload/"+item.ImageName)"*@
        <img class="card-img-top" src="@("/Upload/"+ViewBag.ProfilePicture)" style="width:20%;height:30%;" alt="Card image">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.FirstName @ViewBag.LastName</h4>
            <p class="card-text">@ViewBag.CellNumber</p>
            <p class="card-text">@ViewBag.Email</p>
            <a asp-action="Edit" asp-route-id="@ViewBag.EmpID" class="card-link">Edit Details</a>  |
            <a asp-action="CreateSkill" class="card-link">Add Skill</a>
        </div>
    </div>


</div>


<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.SkillId)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.EmpID)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.SkillName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExperienceInYears)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.HiddenFor(modelItem => item.SkillId)
                    </td>
                    <td>
                        @Html.HiddenFor(modelItem => item.EmpID)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.SkillName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExperienceInYears)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.SkillId })
                </td>
            </tr>
        }
        <tr>
            <td>
            </td>
            <td class="text-info">
                total Years Experience
            </td>
            <td class="text-danger">
                <h3 class="text-dark display-4">@ViewBag.TotalYearsOfExp</h3> 
            </td>
            <td>
            </td>
        </tr>
    </tbody>
</table>

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/Edit.cshtml
@model ExperiencePostCoreWebApp.Models.Employee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AfterLayout.cshtml";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="EmpID" class="control-label"></label>
                <input asp-for="EmpID" class="form-control" readonly />
                <span asp-validation-for="EmpID" class="text-danger"></span>
            </div>*@
            <input type="hidden" asp-for="EmpID" />
            <input type="hidden" asp-for="ProfilePicture" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellNumber" class="control-label"></label>
                <input asp-for="CellNumber" class="form-control" />
                <span asp-validation-for="CellNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" accept="image/*" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details">Back to Dashboard</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/Index.cshtml
@model ExperiencePostCoreWebApp.Models.Employee

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_BeforeLayout.cshtml";
}

h1>Welcome to Employee Experience Post Portal </h1>

<h4>Login</h4>
<hr />
<div class="row">
    <div class="co<l-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
                <a asp-action="Create" asp-controller="ExperiencePortal" class="btn btn-info">SignUp</a>
            </div>
        </form>
        <div class="text-dark">@ViewData["Status"]</div>

    </div>
</div>

<div class="bg-dark text-light">
    <marquee direction="left">
        www.experiencepost.com
    </marquee>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EFCoreRepositoryPatternDemo/Views/ExperiencePortal/ViewEdit.cshtml
@model ExperiencePostCoreWebApp.Models.Employee

@{
    ViewData["Title"] = "ViewEdit";
    Layout = "~/Views/Shared/_AfterLayout.cshtml";
}

<h1>ViewEdit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ViewEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpID" class="control-label"></label>
                <input asp-for="EmpID" class="form-control" />
                <span asp-validation-for="EmpID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellNumber" class="control-label"></label>
                <input asp-for="CellNumber" class="form-control" />
                <span asp-validation-for="CellNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePicture" class="form-control" />
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}